### PR TITLE
Fix negative sign

### PR DESCRIPTION
**Pull request by dalev**
(Marked as 'Draft' because this extends my previous PR #25)

- Handle attribute `dir="-"` in one additional place. 

- The interpretation of `~0` was off:  I noticed a failure using `(make-VkSubpassDependency VK_SUBPASS_EXTERNAL ...)`:  before this PR, that constant's value is `-1`, but IIUC it should be `#xffffffff` because the `srcSubpass` field has type `uint32_t`.  (I'm far from knowledgable about Vulkan, but it seems like `vk.xml`'s usage of `~0U` is a bug -- it assumes that an `unsigned int` is 4 bytes.  Generating code that uses the client's value for `(ctype-sizeof _int)` is probably not worth the trouble:  if that value is not 4, then the expression evalutes to the wrong answer.)

### CODE REVIEW

**Comment by zyrolasting** [comment]
Thanks for this. If I use `-1`, it's either because of something I saw in the Vulkan registry, or because Racket treats `-1` as I'd expect for a particular operation. Can you remind me of the parts of the registry I got wrong here?

**Comment by dalev** [comment]
Try running the below program with your latest vulkan package installed; I observe this error:
```
; ptr-set!: given value does not fit primitive C type
;   C type: _uint32
;   value: -1
```
Racket's FFI deems -1 to be incompatible with _uint32, which is the type of the first field in the VkSubpassDependency struct.  It does not "automatically" convert to #xFFFFFFFF.

Program:
```
#lang racket/base
(require vulkan/unsafe)
(make-VkSubpassDependency
     VK_SUBPASS_EXTERNAL ;(srcSubpass _uint32_t)
     0 ; (dstSubpass _uint32_t)
     VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT ;(srcStageMask _VkPipelineStageFlags)
     VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT ;(dstStageMask _VkPipelineStageFlags)
     0 ;(srcAccessMask _VkAccessFlags)
     VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT ;(dstAccessMask _VkAccessFlags)
     0 ;(dependencyFlags _VkDependencyFlags)
     )
```

**Comment by dalev** [comment]
(I extracted just the relevant diff here, instead of basing it on another PR.)

**Comment by zyrolasting** [comment]
I'm good with this. Thanks much for following the maintenance notes.

**Pull request merged**
